### ISSUE TITLE
Add unecessary empty lines on pom.xml 

### ISSUE THREAD

**Issue by ericdallo** [nnichols/clojure-dependency-update-action#11] opened 2022-03-23 14:56 UTC
v4 seems to add empty lines everytime it needs to update pom.xml

examples:

https://github.com/clojure-lsp/clojure-lsp/pull/854/files
https://github.com/clojure-lsp/clojure-lsp/pull/855/files

**Comment by ericdallo** [comment] 2022-06-06 00:33
@nnichols Could you help with this please? I'm ATM closing PRs and manually updating the deps because fo this :(
https://github.com/clojure-lsp/clojure-lsp/pull/1011

**Comment by nnichols** [comment] 2022-06-11 18:31
@ericdallo This took a long time to mentally unwind, but I found the root cause in antq and have opened a PR to fix it here: https://github.com/liquidz/antq/pull/165

I'll let you know when that gets merged, and run a test against a sample repo

**Comment by ericdallo** [comment] 2022-06-11 18:39
Awesome! Thank you for your efforts!

**Comment by nnichols** [comment] 2022-06-13 21:10
@ericdallo This is looking good when running `antq` from the command line, and executing the action against my test repo has been successful as well. Please let me know if everything looks good on your end. The action automatically pulls the most recent release of `antq` so no changes should be required on your end.

**Comment by ericdallo** [comment] 2022-06-13 23:57
Amazing @nnichols, thank you very much for the help!
I let you know as soon as I check the next bump PR

**Comment by nnichols** [comment] 2022-06-23 14:53
@ericdallo Based on this [Pull Request](https://github.com/clojure-lsp/clojure-lsp/pull/1078/files), I believe this issue is resolved. If you see it happen again or any other odd-behavior, please let me know!

**Closed by nnichols** 2022-06-23 14:53 UTC

**Comment by ericdallo** [comment] 2022-06-23 15:58
Yes, thank you very much!
